services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./psql:/var/lib/postgresql/18
  kafka:
    image: apache/kafka:latest
    # network_mode: host
    environment:
      DOCKER_HOST_IP: 192.168.196.206
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.196.206:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
  # garage:
  #   image: dxflrs/garage:v2.1.0
  #   ports:
  #     - 3900:3900
  #     - 3901:3901
  #   volumes:
  #     - ./garage/config.toml:/etc/garage.toml:ro
  #     - ./garage/data:/var/lib/garage

  s3mock:
    image: adobe/s3mock:latest
    ports:
      - 9090:9090
    environment:
      COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS: "mock"
      COM_ADOBE_TESTING_S3MOCK_STORE_REGION: "mock"
      COM_ADOBE_TESTING_S3MOCK_STORE_ROOT: "/data"
    volumes:
      - ./s3mock:/data
