services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./psql:/var/lib/postgresql/18
  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
  # garage:
  #   image: dxflrs/garage:v2.1.0
  #   ports:
  #     - 3900:3900
  #     - 3901:3901
  #   volumes:
  #     - ./garage/config.toml:/etc/garage.toml:ro
  #     - ./garage/data:/var/lib/garage

  s3mock:
    image: adobe/s3mock:latest
    ports:
      - 9090:9090
    environment:
      COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS: "mock"
      COM_ADOBE_TESTING_S3MOCK_STORE_REGION: "mock"
      COM_ADOBE_TESTING_S3MOCK_STORE_ROOT: "/data"
    volumes:
      - ./s3mock:/data
